# Generated by Django 3.2.9 on 2021-12-07 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=20)),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그목록',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(db_index=True, max_length=100)),
                ('photo', models.ImageField(upload_to='mall/shop/%Y/%m/%d')),
                ('content', models.TextField()),
                ('tag_set', models.ManyToManyField(blank=True, to='mall.Tag')),
            ],
            options={
                'verbose_name': '가게이름',
                'verbose_name_plural': '가게목록',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.shop')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글목록',
            },
        ),
    ]
