# Generated by Django 3.2.9 on 2021-12-08 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그목록',
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('birth', models.CharField(max_length=10)),
                ('ent', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('content', models.TextField()),
                ('tag_set', models.ManyToManyField(blank=True, to='wannaone.Tag')),
            ],
            options={
                'verbose_name': '멤버',
                'verbose_name_plural': '멤버들',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wannaone.star')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글목록',
            },
        ),
    ]
