# Generated by Django 3.2.9 on 2021-12-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
