# Generated by Django 3.2.9 on 2021-11-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('subject', models.CharField(max_length=100, verbose_name='주제')),
                ('Reference', models.URLField(verbose_name='참조')),
                ('date', models.DateField(verbose_name='날짜')),
                ('content', models.TextField(verbose_name='내용')),
            ],
        ),
    ]
