# Generated by Django 3.2.9 on 2021-11-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목:')),
                ('fan_name', models.CharField(max_length=5, verbose_name='닉네임:')),
                ('url', models.URLField(blank=True, verbose_name='출처:')),
                ('content', models.TextField(verbose_name='내용:')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='사진:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
