# Generated by Django 3.2.9 on 2021-11-30 20:49

from django.db import migrations, models
import fan.upload_to


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fan_name',
            field=models.CharField(max_length=20, verbose_name='닉네임:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to=fan.upload_to.uuid_name_upload_to, verbose_name='사진:'),
        ),
    ]
